### ISSUE TITLE
App store says "open" instead of update

### ISSUE THREAD

**Issue by gbertb** [ArtSabintsev/Siren#120]
The alert shows up, takes me to the app store. I click on "open" (instead of "update"), and it took me back to the app. Round and round it goes... any clues? 

The app is in the US and it's been >10 hrs since it was released on the app store. https://itunes.apple.com/lookup?bundleId=org.litterati.LitteratiApp looks updated.

Went from 1.7.2 to 1.8.0

**Comment by getaaron** [comment]
Looks like the iTunes API is reporting the latest version but it hasn't propagated to your App Store yet.

We could try adding an optional 24 hour buffer with `currentVersionReleaseDate` but in my experience the App Store and iTunes API are updated very close to each other.

**Comment by ArtSabintsev** [comment]
@gbertb I would not recommend using `.Force` for new app releases, as the JSON has a tendency to be updated before the app gets propagated to the App Store CDN.

The `.Force` option is in there for those people who wrap Siren around some logic using a configuration file on the backend. They tend to change a flag on the server that makes Siren launch in `.Force` mode for those with out of date applications, and they tend to do it many days if not weeks after a new version goes live (to avoid the situation you're currently seeing).

This is more of an Apple problem than  Siren problem, and has been a PITA since mid 2016. Nothing we can do about it.

Closing the issue, but feel free to follow up to this issue.

**Comment by gbertb** [comment]
Thanks for the quick reply. 
The user was able to delete the app, and reinstall to the latest version. Would that still makes sense if the user was able to download the latest version from the store?
@ArtSabintsev

**Comment by ArtSabintsev** [comment]
That's a coincidence. It might have been available in the app store the moment or two after he deleted the app and tried again. Like @getaaron and I have said, there are propagation issues with the App Store these days.

**Comment by gbertb** [comment]
Gotcha, thanks!

**Comment by sherm4n90** [comment]
@ArtSabintsev Im having the same problem in the AppStore. The lookup returns the latest version and also the AppStore app shows the option to update the current version, so this means the new version is ready in my territory. 
Im using:
`siren.majorUpdateAlertType = .Force
  siren.checkVersion(.Immediately)` 
But the update alert still does not appear.
Testing in the simulator it is shown correctly though.

**Comment by ArtSabintsev** [comment]
Could you please open a ticket, since your problem is different?

Thank you.

**Comment by ArtSabintsev** [comment]
Hey - just wanted to let you know that this issue has been fixed as of v2.0.0: https://github.com/ArtSabintsev/Siren/releases/tag/2.0.0
