### ISSUE TITLE
How to set alert delay time for an hour or other?

### ISSUE THREAD

**Issue by ufosky** [ArtSabintsev/Siren#151]
I have found the property `showAlertAfterCurrentVersionHasBeenReleasedForDays` for set delay time after release.  Because 1 day is too long and 0 day may cause some issue, I just want to set delay time to 1 hour, but the property  `showAlertAfterCurrentVersionHasBeenReleasedForDays` is an `Int` value, I cannot set a time interval like 1 hour. I suggest add an interface for set delay time use `TimeInterval`, because this is more general in Swift.

**Comment by ArtSabintsev** [comment]
You can't do that and I have no plans to add that feature. 1 day is a very safe bet from experience, since propagation of the binary to App Store CDN's is variable. Trust me on this, as I've been maintaining this library and the Obj-C counterpart for almost 5 years, and this delay is from experience.

Feel free to fork the library and add the feature for your own use.

Closing this issue, but feel free to respond and I'll follow up.
