### ISSUE TITLE
Is there anyway to use this library for Enterprise Program of Apple?

### ISSUE THREAD

**Issue by suadbay** [ArtSabintsev/Siren#170]
Hi,

We have an internal app we are using in-house. For that we just joined Apple's enterprise program. So we are not going to use App Store.

The way to update the app for company's devices is that we have to provide them a link. And then they can go to the link and update the app.

I was wondering if is there anyway I can use this library to check the URL that is used to update the app?  And if there is any update detected, show them the warning and update the app automatically

**Comment by ArtSabintsev** [comment]
There isn't, since a custom backend would need to be written. There's no way to guarantee that each company creating a backend would follow a spec, even if I defined it here. To avoid the headache, Siren does not offer this capability.

However, Siren is Open Source, so you're welcome to swap out the URL that's used for your own, and then make sure you provide, at a bare minimum, a JSON payload that provides the values that are defined here: https://github.com/ArtSabintsev/Siren/blob/master/Sources/SirenLookupModel.swift#L22-L25
