### ISSUE TITLE
Carthage Build Fails on Swift 4.2

### ISSUE THREAD

**Issue by danielmhanover** [ArtSabintsev/Siren#230]
This was already brought up in [this issue](https://github.com/ArtSabintsev/Siren/issues/225).

I just wanted to say the issue seems to persist and that a quick fix is to replace `UIWindow.Level.alert` with `UIWindowLevelAlert` in `SirenUIAlertControllerExtension.swift`.

**Comment by ArtSabintsev** [comment]
Hey - thanks for the message. That seems a bit weird, since https://developer.apple.com/documentation/uikit/uiwindow/level states that `UIWindow.Level` is the appropriate approach. Are you positive you're using Xcode 10 and it's that Carthage is using the Xcode10 `xcodebuild` toolchain?

**Comment by danielmhanover** [comment]
Yes I am certain that I am. I’m not sure why this is happening but if it doesn’t impair functionality, making this replacement might be beneficial.

**Comment by ArtSabintsev** [comment]
Can you send me a zip file with a blank sample project that tries to bring in Siren using Carthage? I’ll try to replicate it on my end afterwards. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stevenp** [comment]
This doesn't appear to be limited to Carthage. I'm building on the latest Xcode 10.1 beta using Cocoapods and I was also unable to compile due to this same error. 

I had a workaround in my Podfile that was setting the Swift version at the Pods project configuration level and deleting it for every Pod target, which ended up leaving me with Siren trying to compile with Swift 4 instead of 4.2. This code doesn't compile unless the target is explicitly set to 4.2, which is what was likely causing the error in this issue. I was able to remove my workaround now that my dependencies all work with Swift 4.2, and that resolved this problem for me.

**Comment by ArtSabintsev** [comment]
So everything is working now?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stevenp** [comment]
For me, at least, it is.
