### ISSUE TITLE
hideWindow()  causes a crash

### ISSUE THREAD

**Issue by rex3du** [ArtSabintsev/Siren#24]
When the alert pops up and user presses home button and go back app again. Tap "Next Time" or "Update" will cause a bug. 

I found the hideWindow()  cause this issue. you need to check the updateWindow if nil before hide it. 
Please fix this, thanks.

**Comment by ArtSabintsev** [comment]
Hey,

Would you mind making a sample project delineating the problem and solution?

I've never come across this issue.

Thanks!

**Comment by rex3du** [comment]
@ArtSabintsev  
Please just use your sample project and add   

func applicationWillEnterForeground(application: UIApplication) {
        Siren.sharedInstance.checkVersion(.Immediately)
}
func applicationDidBecomeActive(application: UIApplication) {
       Siren.sharedInstance.checkVersion(.Daily)
 }

into your delegate class. Try open the app and press home button and go back again. Clicking the next time button will crash the App.

**Comment by m-herold** [comment]
Hi,

I think that ```checkVersion(_:)``` with parameter ```SirenVersionCheckType.Immediately``` should not be called from ```applicationWillEnterForeground(_:)``` and/or ```applicationDidBecomeActive(_:))``` because that could lead to several alerts displayed on top of each other (e.g. in the situation that rex3du described) which can be a problem when not using ```SirenAlertType.Force``` (like shortly mentioned in the readme).

When using any other ```SirenAlertType``` where the alert can be dismissed the ```hideWindow()``` gets called each time you close the alert - at least when using ```UIAlertController``` (iOS 8).
In this method ```Siren.updaterWindow``` is set to null (#515) which leads to a crash when closing the second alert (#514: *"unexpectedly found nil while unwrapping an Optional value"*).

When you need to call ```checkVersion(.Immediately)``` from e.g. ```applicationWillEnterForeground(_:)``` and you do not want to have several alerts on top of each other I would suggest executing the code in ```checkVersion(_:)``` only if ```Siren.updaterWindow``` is nil.


Thanks for your great work on this excellent project!

**Comment by rex3du** [comment]
@m-herold  your are correct. checkVersion(.Immediately) causes the issue. @ArtSabintsev  I suggest remove the example in the Setup Instruction which is using checkVersion(.Immediately) from e.g. applicationWillEnterForeground(_:).

**Comment by ArtSabintsev** [comment]
Will look into this after the Swift 2 branch is merged.

**Comment by ArtSabintsev** [comment]
Fixed in Swift 2 branch.

Thanks!
