### ISSUE TITLE
Question on custom rules

### ISSUE THREAD

**Issue by crspybits** [ArtSabintsev/Siren#274]
I'm thinking of making my forced updates depend on a custom rule phrased like "force an update when a patch number is an odd number (e.g., 1, 3, 5 etc)." It looks like Siren currently doesn't allow for such customizations. If so, would you be open to a PR that does add this possibility? Thanks!

**Comment by ArtSabintsev** [comment]
Hey, thanks for the question. 

Is that a real rule you want to add? If not, can you present me with an example of a rule that you’re looking to add and the reasoning for it? Depending what the rule is, I can either walk you through a custom solution that you can roll in your app, or potentially build it into the library .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by crspybits** [comment]
Hey, thanks for the quick response. Yes, it is a real rule. Here's my use case. I want to force an update of the app under particular app version conditions. Basically, I want to encode that "force update" information in the app version. It will be an edge case when I want to force the update. (I'm thinking of it now because I have a breaking change on my server that will necessitate a corresponding breaking change on the app.). 

I don't want to force the update based on simply increasing major, minor, or patch values in the version. Again, because this is an edge case for me. So, using something like odd numbers in the minor version to force the update is one way to do this. Of course, this will require paying careful attention to creating version numbers for releases of the app. Don't want to mistakenly give an odd minor version number in a release when  an app update is not required. Bad UX in that case.

Does this make sense?

**Comment by ArtSabintsev** [comment]
Hey,

I'm going to put on my architect's hat and tell you that this is not a good idea. How we solved this problem when I worked at The Washington Post was as follows:

- Ping a separate location on some server, or Amazon S3 (or create an API) that returns the list of all versions that require a force upgrade
- On launch, check that remote file/API if the current installed version is one of the versions that requires a forced upgrade
- If that's `true`, provide a force upgrade.

Conversely, you can check to see what the latest version is in the App Store and program your server/static-file to return `true` for force upgrade for that version if that's how you want to deal with it. This one way would be easier in my opinion - less juggling of files and less retaining values.

So, let's say version 1.2.5 requires a forced upgrade, your server would essentially return `1.2.5` for the `force_upgrade.json` file or `force_upgrade` API and then on launch, your app would compare that version to what's currently installed. If the currently installed version is less than and not equal to the latest force upgrade version, you force an upgrade. Otherwise, do-nothing/business-as-usual.

Doing weird custom rule logic around oddly-pointed values is absolutely the wrong way to solve this problem.

I hope this helps!

Closing the issue, however, I'm happy to continue the discussion if you need more guidance/thoughts.

**Comment by crspybits** [comment]
Hey, it's cool if you don't think this appropriate for your library. I think this is not a matter of absolutes though. Sometimes simple methods are good. And some projects do make clear distinctions based on odd/even number version components (e.g., https://stackoverflow.com/questions/1266411/which-open-source-projects-use-odd-unstable-even-stable-style-of-versioning/1266481#1266481).

**Comment by ArtSabintsev** [comment]
Hey,

Thanks for that interesting history lesson. I'd never heard of any project acting this way. Looks like many of those projects mentioned dropped the practice. 

I guess my thought for your situation is that you have a server already in place, so it wouldn't be too far of a stretch to expose one more API for force-upgrade monitoring. 

I think your scenario is very niche, so I wouldn't want it in Siren, however, you could follow the `customAlertRulesExample` in the AppDelegate file in the example project and grab the AppStore version of the app on the returned `lookupModel` and from there, perform another Siren request. that does a force upgrade if the version is odd. 

Does that make sense?
