### ISSUE TITLE
Using Siren in an Objective-C Project

### ISSUE THREAD

**Issue by mogelbuster** [ArtSabintsev/Siren#290]
Is there any documentation or examples of using Siren in an Objective-C iOS application?  Is this possible?  I apologize if this isn't the correct forum, but I haven't been able to find any information online.  I know I could use Harpy, but that is no longer supported.   I was able to include the Siren project with cocoapods, and I imported the auto-generated header with this:
`#import <Siren/Siren-Swift.h>`
This Siren class is being recognized, but the problem I am having is I cannot access the 'shared' static property on the Siren class.  I'm not sure if I'm using the wrong code, or if it is a problem with swift/objective-c interoperability.  Has anyone tried this, and if so, is there any Objective-C code examples using Siren?  I tried `[Siren shared]` and I am getting "No known class method for selector 'shared'."

**Comment by ArtSabintsev** [comment]
Hi! Could you please provide me with a small sample project that’s causing you issues? I can take a look from there.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mogelbuster** [comment]
Hi Arthur,

Thanks for responding so quickly!  I've attached a compressed sample
project.  I put some notes in the AppDelegate.m file in the
applicationDidFinishLaunchingWithOptions method.  You'll see two errors
building there.

Thank you for the help, it is much appreciated!
Kenny

**Comment by ArtSabintsev** [comment]
Hi,

There is no sample project attached.

**Comment by mogelbuster** [comment]
Hi Arthur,

Sorry, I responded in my email and attached it there, but it doesn't look like it made it to github.  Here's a 
[dropbox link to the project](https://www.dropbox.com/s/ip8u12q1e4qkidc/ObjectiveCSiren.zip?dl=0).  Also, I asked a similar question on stackoverflow, and got a [helpful answer](https://stackoverflow.com/a/56434955/1677693).

Thanks again for the help!

**Comment by mogelbuster** [comment]
Arthur,

I have confirmed Andrei's advice (on stackoverflow) about creating a wrapper class for Siren.  It works like a charm!  This would be a great feature to include in Siren.  It would allow Siren to support Objective-C applications, while decoupling the Objective-C support from Siren's functionality, so you can happily use all the latest Swift features.  If I create a github worthy wrapper, I'll make a pull request.

Thank you!

**Comment by ArtSabintsev** [comment]
Alright, confirmed on my end. Adding `objcMembers` to Siren.swift fixes the issue. I'll cut a new version shortly!

**Comment by ArtSabintsev** [comment]
Alright, ignore that last statement. 

The problem I've come across now is that the managers (`APIManager`, `RulesManager`, etc.) can't be customized without converting them to reference types and making them visible to ObjC. 

I'm not sure I want to do that as I tend to follow the 80-20 rule. I write code that solves problems for 80% of users, and since this is the _first time_ in 4+ years someone has even brought up this issue about interoperability, I feel that your specific use case falls in the 20% bucket.

With that being said, the way for me to allow for this to be easier for you is to convert the managers to `NSObject` subclassed reference types, and I'm not sure if I want to do that. 

So, this goes back to your `wrapper` class idea. I could create an ObjC wrapper for Siren and the managers in a way that makes Siren visible to Objective-C and offer it as a subspec.

I'll sleep on it and get back to you.

Thanks for the sample project!

**Comment by ArtSabintsev** [comment]
Sorry, been pretty busy, but I have not forgotten about this request. It’s still on my to-do list.

**Comment by ArtSabintsev** [comment]
Alright, I've had a lot of time to think about this issue. 

The original goal of Siren was be a Swift alternative to my ObjC project, [Harpy](https://github.com/ArtSabintsev/Harpy). However, as I have deprecated Harpy, I understand that you, and my others, may want to use Siren in your existing ObjC codebase. 

Unfortunately, your use case is one that doesn't follow the 80-20 rule. While I understand that many projects exist that are 100% Objective-C, or that have mixed codebases, I don't believe that language is the future of the iOS platform. 

Therefore, I do not want to make changes that I consider to be regressive in the long term.

You're welcome to use Harpy, as the base functionality should still work just fine, as it has worked with minimal changes for many years now.

Thanks again for your request.
