### ISSUE TITLE
force update an application already on store.

### ISSUE THREAD

**Issue by JhonnyTawk** [ArtSabintsev/Siren#334]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: YES 
- **What is your app's Bundle ID?**: 
- **When was the latest version of your app published to the App Store?**:  
2019
- **Is your app published in the US App Store? If not, what App Store is it published in?**: 
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:

---
I have an application already on the store and we made design refactoring and updated the application UI and API's I want to force all users to update to the latest version
The application on the store does not include Siren But the version I am submitting include Siren 

`

            static` func initForceUpdate() {
            let siren = Siren.shared
             siren.presentationManager = PresentationManager(alertTitle: "UPDATE".localized(),
                                                        nextTimeButtonTitle: "NEXT_TIME".localized())
                //REMEMBER: - Change this to Force
        //        let rules = Rules(promptFrequency: .immediately, forAlertType: .force)
        //        siren.rulesManager = RulesManager(globalRules: rules, showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
                siren.rulesManager = RulesManager(globalRules: .critical)
        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }`

will this be enough so when I submit a new version to all user can be able to update the App?

**Comment by ArtSabintsev** [comment]
Yes, this should be enough, but keep in mind that if you do this and the app is still propagating to the App Store CDNs, your users will be in an infinite loop between launching the app and being prompted to download an app that may not be ready to download from the App Store. 

The JSON updates faster than the binary is available to download.

Since this is a design decision and not about sex, I recommend that you change the number of days parameter from 0 to 1.

And if I may give you one more piece of unsolicited feedback, users hate being forced to update their apps on launch. I would strongly recommend not pushing users to do that unless it’s a bug fix that fixes your app from crashing 100% of the time.

**Comment by JhonnyTawk** [comment]
concerning the loop between launching the app and being prompted so in order to solve that in case it would happen, we set `showAlertAfterCurrentVersionHasBeenReleasedForDays ` to `1`

for the force update after app transfer and updating the whole UI and all the BE it is logically that users must update to enjoy the full experience of the product at least the first time.

**Comment by ArtSabintsev** [comment]
yup, that sounds fine. I just wanted to make it clear so you would avoid any potential issues. 

Looks like this is resolved now.

Closing the issue.
