### ISSUE TITLE
Was it really necessary to make the minimum version iOS 13?

### ISSUE THREAD

**Issue by yusuftor** [ArtSabintsev/Siren#362]
My app uses Siren and as much as I'd love to make my app support iOS 13+ I can't due to the number of users we have on iOS 12 and iOS 11. I now can't use any version of Siren higher than 5.7.1. Looking at the release notes it seems it hasn't been upgraded for a specific technical reason. Please can you reverse that decision? Thanks!

**Comment by ageevvalentin** [comment]
I am of the same opinion. Most of the libraries target the minimum version that the Xcode supports (iOS 9).

**Comment by ArtSabintsev** [comment]
Hey all,

Thanks for your feedback.

I'm not coding much these days, so I want to mitigate risk and expectations for older versions. 

As I work for a large company, and we have made the decision to begin moving from iOS 12 toward iOS 13 in the next release, I figured that most companies that are smaller would most likely be in the same boat or have already made the transition that we are about to make.

I took a look back at [Apple's metrics](https://developer.apple.com/support/app-store/) and realized that the VAST majority of the general population is on iOS 13+ at this point in time, and there was no reason to support older versions, since I can't really test against them, nor do I see a need to test against them (and I don't want to either).

I also am thinking about upgrading this library to utilize Combine (or maybe the forthcoming async/await API) in a couple places, so moving this to iOS 13 sends the signal, _ahead of time_, that I plan on only worrying about iOS 13+ moving forward.

I know this isn't the answer you want, but there are no massive changes in the last couple releases (tvOS support and Turkish Localization adjustment), so you aren't missing out on anything.

If you look at the history of releases of this library, it's essentially been in maintenance mode for a couple years now and it will remain this way for the foreseeable future.

I'm happy to answer questions but I do not plan on changing my position at this time.

**Comment by ArtSabintsev** [comment]
I forgot to mention that there are also framework compilation improvements in some minor version iOS 12.x version, but I couldn't recall which one. iOS 13 made sense as it's visible there.

Also, if it's any consolation, I don't have any plans to move the minimum base again for a long time.
