### ISSUE TITLE
Testing using a different bundle id does not work

### ISSUE THREAD

**Issue by varun-s** [ArtSabintsev/Siren#368]
Trying to test using a different bundle id as recommended (Since app is still to be released).
Seems to work only on simulator.
On actual device, build fails.

**Comment by ArtSabintsev** [comment]
The build fails because your Apple Dev Account probably doesn't own the bundleID you're testing. No way around this without using a real bundleID that's live in the store. Sim testing is enough to test this SDK until you're first version is out, unless you want to ship Siren with your second version so you can test it on a physical device.

**Comment by varun-s** [comment]
Thanks for the feedback
