### ISSUE TITLE
Close Alert programmatically

### ISSUE THREAD

**Issue by nickp4488** [ArtSabintsev/Siren#374]
Hello,
I use siren for app update notifying user.
I also use my own custom view if backend server flag enabled. I need to dismiss default siren alert when this custom view open/shown.

**How can I dismiss siren alert programmatically?**
Is this possible currently?

Thank you,

**Comment by ArtSabintsev** [comment]
hello - unfortunately you cannot do this easily, since Siren does not pass back a reference. You could search the window hierarchy for it (probably), but it's not guaranteed to work. 

Alternatively, you can always wait to call Siren until after you've done your server check and can guarantee that's succeeded.
