### ISSUE TITLE
Siren has issue of reading version if at the end is added '.0'

### ISSUE THREAD

**Issue by Emin-Emini** [ArtSabintsev/Siren#382]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

My project version was 2.1, and on the App Store when we submitted we put 2.1.0.
For some reason, Siren reads 2.1 older than 2.1.0. And this made users unable to use the app, cause the alert is showing all the time.

Please fix this issue!

**Comment by ArtSabintsev** [comment]
Hmm what happens if you submit 2.1.1 now? Should get around this issue.

That is an edge case scenario that Siren doesn't support at the moment, nor did I think Apple would allow.

If you went from 2.1 --> 2.1.1 it should have worked.

I will not be addressing this edge case at this time.

Thanks for reporting it!
