### ISSUE TITLE
daily, weekly not working

### ISSUE THREAD

**Issue by EzimetYusup** [ArtSabintsev/Siren#6]
daily , weekly parameters not working properly , it is always using immediately parameter .

**Comment by ArtSabintsev** [comment]
Hey @EzimetYusup 

I can confirm that there is a bug. I think it's due to code in 2 places. Looking into it now.

**Comment by ArtSabintsev** [comment]
All fixed and pushed to cocoapods. Thanks for pointing out the issue!

**Comment by sequeirareema** [comment]
1)How can we Put a custom Alert with our own message .
2) Also . immediately parameter  doesn't put alert if the App Store build is less than 1 day old. Any inputs on this is appreciated

**Comment by ArtSabintsev** [comment]
Hi, please see the:

- AppDelegate in the Example app for how to put up a custom alert
- There is no way to show an app sooner, since Apple takes 24-48 hours to propagate the build across their network. That's why the setting is in there.

In the future, please don't resurrect a 5 year old issue, but feel free to open a new one, as the SDK has changed countless times since then.

Thanks!
