### ISSUE TITLE
Mac App Store support

### ISSUE THREAD

**Issue by tbaranes** [ArtSabintsev/Siren#76]
It would be great to have only one library to handle all the platforms 🎉 
Not sure how hard it would be to port to Siren to macOS, probably just be the interface part which has to be platform related.

**Comment by ArtSabintsev** [comment]
You mean support for the Mac App Store?

**Comment by ArtSabintsev** [comment]
This library is store-dependent.

**Comment by tbaranes** [comment]
Yeah, I mean for the Mac App Store. It won't be useful for `Siren` to support apps outside of the app store since it's a fully different process.

**Comment by ArtSabintsev** [comment]
I'm not sure what it would take to get that working as I've only built a few trivial mac apps in the past couple of years. I'm sure the web request check is similar. The only part that's different is how the alerts are presented.

Is there a library that already does this? If so, I can take a look at what they're doing.

**Comment by tbaranes** [comment]
[iVersion](https://github.com/nicklockwood/iVersion) does this. The main difference between `Siren` and `iVersion` is the final output: `iVersion` displays the full changelog whereas `Siren` display just a message. 

For the alerts, you can replace the `UIAlertController` by a `NSAlert`, the API is really straight forward, and the output quiet similar.

**Comment by ArtSabintsev** [comment]
ok cool - I'll look into this soon. 

Thanks for the suggestion!

**Comment by ArtSabintsev** [comment]
Keeping the issue open until I get a PR opened.

**Comment by ArtSabintsev** [comment]
Alright, I've bene thinking about this since breakfast.

My current interests are in iOS dev and backend development using Swift 3. Due to that, and the precious little time I have, I don't really want to build this feature myself as I am not that proficient with the macOS APIs, nor the Mac App Store, which Apple seems to have indirectly acknowledged isn't doing well during this past WWDC (I forgot what they changed, but whatever it was made it easier for macOS developers to do things outside the Mac App Store).

With that in mind, I will not be doing the work for this myself, however, if this is something you would like to build, I will happily look into any PR that's submitted and help with testing at that point in time.

Thank you for understanding.

Closing this issue, but feel free to continue the conversation here - I will definitely respond.

**Comment by tbaranes** [comment]
I fully understand that! I will take a look into this when I will have time.
Anyway, thanks for creating and maintaining that awesome library 👍

**Comment by ArtSabintsev** [comment]
You're very welcome! I look forward to your PR in the future!

Have a great day and thanks again for the request.
